"""initial schema with extended hours

Revision ID: e3be7251e5c1
Revises: 
Create Date: 2026-02-18 19:05:25.658916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3be7251e5c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'execution_extended_hours', sa.Boolean(), nullable=False,
            server_default=sa.false()
        ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('execution_extended_hours')

    # ### end Alembic commands ###
